#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-openid
Version  : 2.2.5
Release  : 7
URL      : https://files.pythonhosted.org/packages/7b/8a/e94d18c666073280b8c0614b7e38cfaf0b129989e42f4ca713942b862f0a/python-openid-2.2.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/7b/8a/e94d18c666073280b8c0614b7e38cfaf0b129989e42f4ca713942b862f0a/python-openid-2.2.5.tar.gz
Summary  : Python 3 port of the python2-openid library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-openid-license = %{version}-%{release}
Requires: python-openid-python = %{version}-%{release}
Requires: python-openid-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Python OpenID library example code
==================================
The examples directory contains working code illustrating the use of
the library for performing OpenID authentication, both as a consumer
and a server. There are two kinds of examples, one that can run
without any external dependencies, and one that uses the Django Web
framework. The examples do not illustrate how to use all of the
features of the library, but they should be a good starting point to
see how to use this library with your code.

%package license
Summary: license components for the python-openid package.
Group: Default

%description license
license components for the python-openid package.


%package python
Summary: python components for the python-openid package.
Group: Default
Requires: python-openid-python3 = %{version}-%{release}

%description python
python components for the python-openid package.


%package python3
Summary: python3 components for the python-openid package.
Group: Default
Requires: python3-core
Provides: pypi(python-openid)

%description python3
python3 components for the python-openid package.


%prep
%setup -q -n python-openid-2.2.5
cd %{_builddir}/python-openid-2.2.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583213746
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-openid
cp %{_builddir}/python-openid-2.2.5/LICENSE %{buildroot}/usr/share/package-licenses/python-openid/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-openid/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
